<?php

/**
 * @file
 * Contains tombstones.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tombstones_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tombstones module.
    case 'help.page.tombstones':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal module for handling access to deleted content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function tombstones_node_predelete(Drupal\Core\Entity\EntityInterface $entity) {
  if (\Drupal::service('tombstones.service')->shouldTombstoneBeCreatedFromHook($entity)) {
    \Drupal::service('tombstones.service')->storeTombstonePredeleteMetadata($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function tombstones_node_delete(Drupal\Core\Entity\EntityInterface $entity) {
  if (\Drupal::service('tombstones.service')->shouldTombstoneBeCreatedFromHook($entity)) {
    \Drupal::service('tombstones.service')->createTombstoneForDeletedNode($entity);
  }
}
